version: '3'

services:
  bot:
    build: bot/
    restart: always
    expose:
      - "8000"
    depends_on:
      - selenium
      - db
    networks:
      - my_network 

  selenium:
    image: selenium/standalone-chrome
    container_name: selenium_container
    ports:
      - "4444:4444"
    networks:
      - my_network  

  db:
    container_name: postgres_database
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: frames
    ports:
      - 8000:8000
    expose:
      - "8000"
    volumes:
      - /DataBase:/var/lib/postgresql/data
    restart: always
    networks:
      - my_network 

networks:
  my_network: 